# name of the workflow. if it is omitted, the name file is used instead.
# name for workflow runs
# Specifies the trigger for this workflow.
# -jobs- keyword  to groups together all the jobs that run in this workflow.
# name of jobs
# specific the server to run runner
# groups together all the steps that run in the check-bats-version job
# The uses keyword specifies that this step will run v4 of the actions/checkout action.
# this action setup node in the 14 version
# The run keyword tells the job to execute a command on the runner.
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g bats
    - run: bats -v